
addons:
  apt:
    sources:
    - sourceline: 'ppa:ppa:duggan/bats'
    packages:
    - bats

install:
 - mkdir ~/bin
 - cp varaq-engl ~/bin
 - git clone --depth 1 https://github.com/sstephenson/bats.git ~/bats

before_script:
 - export PATH=$PATH:~/bin
 - export PATH=$PATH:~/bats/bin/bats
script: 
 - echo "\"success\" disp" |perl varaq-engl
 - echo "\"Qapla'\" cha'" |perl varaq-kling
 - echo "\"success\" disp" | varaq-engl
 - test/test.bats
