install:
 - mkdir ~/bin
 - cp varaq-enlg ~/bin

before_script:
 - export PATH=$PATH:~/bin
script: 
 - echo "\"success\" disp" |perl varaq-engl
 - echo "\"Qapla'\" cha'" |perl varaq-kling
 - echo "\"success\" disp" | varaq-engl
