addons:
  apt:
    packages:
    - bats

install:
 - mkdir ~/bin
 - cp varaq-engl ~/bin

before_script:
 - export PATH=$PATH:~/bin
script: 
 - echo "\"success\" disp" |perl varaq-engl
 - echo "\"Qapla'\" cha'" |perl varaq-kling
 - echo "\"success\" disp" | varaq-engl
 - test/test.bats
