language: perl
perl:
 - "5.18"
 - "5.20"
 - "5.22"

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

install: true

script:
  - bats --tap test/test.bats

